---
functional:
  - Пользователь должен иметь возможность искать товары по ключевому слову или категории
  - Пользователь должен иметь возможность фильтровать товары
  - Пользователь должен иметь возможность просматривать товары и просматривать подробную информацию о товаре
  - Пользователь должен иметь возможность добавлять товары в корзину и просматривать содержимое корзины
non-functional:
  - Сайт нужно разработать с учетом удобства использования и оптимизировать для скорости работы
  - Сайт должен быть безопасным и защищать данные пользователя
  - Сайт должен иметь мобильную версию
  - Сайт нужно протестировать на совместимость с последними версиями браузеров
  - Важно, чтобы сайт мог обрабатывать большое количество трафика
  - Сайт должен быть доступен на различных устройствах
implicit:
  - Пользователь должен иметь возможность удалять товары из корзины
  - Сайт должен иметь версию для планшета 
  - Пользователь не должен иметь возможность добавить большее количества товара, чем в наличии
  - Пользователь должен иметь возможность видеть историю заказов
  - Пользователь должен иметь возможность сбросить все выбранные фильтры 
  - В поле фильтра Цена нельзя ввести отрицательное значение
  - В поле фильтра Цена нельзя ввести инные символы, кроме цифр
  - При обновлении страницы сайта должен сохраняться выбранный язык
  - На сайте должна быть единая система вывода товаров на страницах
  - При переключении языков должнен меняться текст языка на сайте
  - Данные о заказе должны отправляться на сервер
  - Верстка сайта должна быть корректна на всех страницах
  - Все изображения на сайте должны быть в едином размере и оформлении
